// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Header: typeof import('./../src/components/header/Header.vue')['default']
    HeaderDropdown: typeof import('./../src/components/header/HeaderDropdown.vue')['default']
    IconAvatar: typeof import('./../src/components/icons/IconAvatar.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconHouse: typeof import('./../src/components/icons/IconHouse.vue')['default']
    IconMenu: typeof import('./../src/components/icons/IconMenu.vue')['default']
    Portal: typeof import('./../src/plugins/portal/Portal.vue')['default']
    PortalTarget: typeof import('./../src/plugins/portal/PortalTarget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../src/components/header/TheHeader.vue')['default']
    UserButton: typeof import('./../src/components/header/UserButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
