// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Filters: typeof import('./../src/views/places/components/filters/Filters.vue')['default']
    FiltersAmenities: typeof import('./../src/views/places/components/filters/FiltersAmenities.vue')['default']
    FiltersButton: typeof import('./../src/components/header/FiltersButton.vue')['default']
    FiltersClose: typeof import('./../src/views/places/components/filters/FiltersClose.vue')['default']
    FiltersPlaceType: typeof import('./../src/views/places/components/filters/FiltersPlaceType.vue')['default']
    FiltersPropertyType: typeof import('./../src/views/places/components/filters/FiltersPropertyType.vue')['default']
    FiltersRadio: typeof import('./../src/views/places/components/filters/FiltersRadio.vue')['default']
    FiltersRange: typeof import('./../src/views/places/components/filters/FiltersRange.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Grid: typeof import('./../src/components/Grid.vue')['default']
    GridItem: typeof import('./../src/components/gird-item/GridItem.vue')['default']
    Header: typeof import('./../src/components/header/Header.vue')['default']
    HeaderDropdown: typeof import('./../src/components/header/HeaderDropdown.vue')['default']
    IconAvatar: typeof import('./../src/components/icons/IconAvatar.vue')['default']
    IconClose: typeof import('./../src/components/icons/IconClose.vue')['default']
    IconDollar: typeof import('./../src/components/icons/IconDollar.vue')['default']
    IconHouse: typeof import('./../src/components/icons/IconHouse.vue')['default']
    IconMenu: typeof import('./../src/components/icons/IconMenu.vue')['default']
    IconStar: typeof import('./../src/components/icons/IconStar.vue')['default']
    Modal: typeof import('./../src/components/Modal.vue')['default']
    PlaceItem: typeof import('./../src/views/places/components/place-item/PlaceItem.vue')['default']
    PlaceItemCreate: typeof import('./../src/views/places/components/place-item/components/PlaceItemCreate.vue')['default']
    PlaceItemEdit: typeof import('../src/views/places/components/place-item/components/PlaceItemEditOrCreate.vue')['default']
    PlaceItemEditOrCreate: typeof import('./../src/views/places/components/place-item/components/PlaceItemEditOrCreate.vue')['default']
    PlaceItemNumberOfGuests: typeof import('./../src/views/places/components/place-item/components/PlaceItemNumberOfGuests.vue')['default']
    PlaceItemReserve: typeof import('./../src/views/places/components/place-item/components/PlaceItemReserve.vue')['default']
    Portal: typeof import('./../src/plugins/portal/Portal.vue')['default']
    PortalTarget: typeof import('./../src/plugins/portal/PortalTarget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserButton: typeof import('./../src/components/header/UserButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
