// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    AuthModal: typeof import('./../src/views/auth/components/AuthModal.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ExampleViewComponent: typeof import('../src/views/home/components/ExampleViewComponent.vue')['default']
    FiltersButton: typeof import('./../src/components/FiltersButton.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Grid: typeof import('./../src/components/Grid.vue')['default']
    GridItem: typeof import('./../src/components/gird-item/GridItem.vue')['default']
    Header: typeof import('./../src/components/header/Header.vue')['default']
    HeaderDropdown: typeof import('./../src/components/header/HeaderDropdown.vue')['default']
    IconAvatar: typeof import('./../src/components/icons/IconAvatar.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconClose: typeof import('./../src/components/icons/IconClose.vue')['default']
    IconHouse: typeof import('./../src/components/icons/IconHouse.vue')['default']
    IconMenu: typeof import('./../src/components/icons/IconMenu.vue')['default']
    IconStar: typeof import('./../src/components/icons/IconStar.vue')['default']
    Modal: typeof import('./../src/components/Modal.vue')['default']
    Portal: typeof import('./../src/plugins/portal/Portal.vue')['default']
    PortalTarget: typeof import('./../src/plugins/portal/PortalTarget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./../src/components/header/TheHeader.vue')['default']
    UserButton: typeof import('./../src/components/header/UserButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
